version: "3"
services:
  db:
    image: mongo:4.0.0
    restart: on-failure
    volumes:
        - mongo_data:/data/db
    ports:
        - "27017:27017"
  app:
    build: .
    command: ["npm", "run", "dev"]
    links:
      - db
    volumes:
      - .:/usr/src
      - node_modules:/usr/src/node_modules
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGO_CONNECTION_STRING=mongodb://db/bbali
      - DEBUG=*
volumes:
  node_modules:
  mongo_data:
